### ISSUE TITLE
Failed params on retry

### ISSUE THREAD

**Issue by raphi** [gzigzigzeo/sidekiq-grouping#10]
Hey @gzigzigzeo, first congrats amazing job, this is exactly what I was searching for (ES bulk indexing with Sidekiq grouping) and it works (almost) perfectly!

I think I've found a bug though: when a job fails, the next time it is retried, it is encapsulated inside multiples arrays (the number of times it failed actually). To be clear, the parameter `data_grouped` of `perform(data_grouped)` is `== [[[[[[[[[["update", "User", 4313]]]]]]]]]]`

Example of trace:
```
2015-11-11T15:26:54.951Z 25819 TID-1237j30 WARN: {"class"=>"ElasticsearchIndexer", "queue"=>"elasticsearch", "args"=>[[[[[[[[[[["update", "User", 4313]]]]]]]]]]], "retry"=>true, "jid"=>"202fbc7c175a06c6010d0943", "created_at"=>1447255614.938022, "enqueued_at"=>1447255614.938174, "error_message"=>"undefined method `constantize' for nil:NilClass", "error_class"=>"NoMethodError", "failed_at"=>1447255614.9496262, "retry_count"=>0}
```

Any idea where it is coming from?

Thank you

**Comment by gzigzigzeo** [comment]
@raphi Hi, thank you for the feedback. It is always pleasant to know that your work is used by other people. It is so OpenSourcy! :) I have created it for the same purpose and never have seen such behavior before. There is nothing about retrying in gem itself. Sidekiq controls it. But I have an idea. It could be the problem with the middleware. Could you please check what job args the failing job has in retry queue? In same time, if you retry the job manually - do you see the retried job in the queue just after clicking the button?

**Comment by gzigzigzeo** [comment]
@raphi Seems I figured out and fixed the problem. Try the last version plz (1.0.2)

**Comment by marshall-lee** [comment]
@gzigzigzeo can this result in some sort of memory leaking? I investigate a memory leak right now and one of the suspects is updated `sidekiq-grouping`.

**Comment by gzigzigzeo** [comment]
@marshall-lee I do not think so, last commit adds just a simple condition in the middleware. And what is leaking?

**Comment by marshall-lee** [comment]
@gzigzigzeo

I don't suspect `sidekiq-grouping` anymore.

Also I found some issue with Chewy https://github.com/toptal/chewy/pull/280 but I don't know if it's the only leaking thing. Maybe there's something else.

**Comment by raphi** [comment]
@gzigzigzeo sorry for the delay... I confirm it is now fixed with the last version. Thank you!

**Comment by gzigzigzeo** [comment]
@raphi Thanks!
