### ISSUE TITLE
Dynamic queues

### ISSUE THREAD

**Issue by florrain** [gzigzigzeo/sidekiq-grouping#11]
Hi!

Thanks for your work @gzigzigzeo this is an amazing job you've done. I'd like to custom the push and the fetch actions for a specific use case but first I'll have a question for you.

From looking at middleware.rb, the jobs using the sidekiq-grouping options are not passed to sidekiq but instead are pushed to a side system. The jobs that don't use any of sidekiq-grouping options are considered "normal" and are passed to Sidekiq.

When a sidekiq-grouping job arrives in the middleware, it is pushed to an independent Redis queue that is named using the pattern "worker_name:queue_name" with the queue_name being the sidekiq_options' queue value and the worker name being the class name underscored.

For me it doesn't look like it needs the queue to be declared in sidekiq.yml and so using dynamic named queues is totally possible as long as the fetching is modified in consequence. Does that sound right?

Thanks.

**Comment by gzigzigzeo** [comment]
@florrain 

Hi! Thank you!

Well, in some sense that's true. But the way of implementing such dynamics in this gem is some kind of workaround. The more correct way of making the dynamic queries work is rolling the custom fetcher based on the default BasicFetch: https://github.com/enova/sidekiq-rate-limiter/blob/master/lib/sidekiq-rate-limiter/fetch.rb, for example.

Unfortunately, Sidekiq does not support fetching strategies chaining, so implementing the custom strategy will break the compability with gems using their own strategies like sidekiq-limit_fetch, or sidekiq-rate-limiter. That was the main reason why I used the trick with middlewares. I wanted to keep the transparency.

So, using of the dynamic queues is possible, but if I wanted to implement it - I'll better started with my own fetching strategy. Take a look on https://github.com/brainopia/sidekiq-limit_fetch - it supports queue control and dynamic queues. Probably it will help.

**Comment by florrain** [comment]
Okay that makes sense. After spending a few hours on the gem I think I found a way to customize it to my need without actually too much pain and keeping the "dynamic" part outside of Sidekiq (i.e in the gem's objects).

I would prefer not adding any other library and risk stability or incompatibilities with Sidekiq Pro which I'm using. Plus I don't need that many features.

Sidekiq is actually fun to play with!

Thanks again.
