### ISSUE TITLE
Key locking is non-atomic

### ISSUE THREAD

**Issue by skwp** [gzigzigzeo/sidekiq-grouping#20]
We're about to make a PR for this but wanted to show a situation where this is a problem. 

https://github.com/gzigzigzeo/sidekiq-grouping/blob/53cb7e41620dcc6de341b67435d44f3847e484a9/lib/sidekiq/grouping/redis.rb#L59

This line of code sets the expiry of a lock but is not atomic with acquiring the lock. We had a situation where the code apparently exited prior to being able to set the expiry on the lock, leading to a locked batch that never flushed.

**Comment by Jared-Prime** [comment]
👍  saw similar deadlock issues; awaiting @skwp PR to compare situation /cc @mstruve

**Comment by gzigzigzeo** [comment]
@skwp I agree, that could be a problem. Your request would be welcome. I do not know why, GitHub does not notify me on new issues/PR's in this repo. So, I am really sorry for delayed answers. Will try to figure out why this happens.

**Comment by skwp** [comment]
@gzigzigzeo I finally fixed this, please see PR #22
