### ISSUE TITLE
poll_interval config option not taken in count

### ISSUE THREAD

**Issue by twonegatives** [gzigzigzeo/sidekiq-grouping#24]
Readme file notes a `poll_interval` config option:
```ruby
Sidekiq::Grouping::Config.poll_interval = 5 # Amount of time between polling batches
```
`Sidekiq::Grouping::Config` sets its initial value to 3, and the issue here is that this value can be changed, but it would have **no effect** on actual polling interval. As long as gem code gets loaded before rails application's initializers, we get `Concurrent::TimerTask` started with default `execution_interval` value due to this line in `grouping.rb`:
```ruby
Sidekiq::Grouping.start! if Sidekiq.server?
```
I guess the reason why this was not noticed before is the `Sidekiq::Grouping::FlusherObserver` which prints nothing on a non-exception-raising execution result. Adding `logger.info` for each `update` on a fresh rails application with `poll_interval` set to non-default value confirmed the issue.

I'm not sure which solution would suite you the best, so let me first suggest a couple of ideas:
- We could move configuration options to .yml file
- Or may be get `Sidekiq::Grouping.start!` out of gem main .rb file and force users to write it by hands

Please tell me what you think and I'll be happy to make a pull request!

**Comment by gzigzigzeo** [comment]
Thanks, really good point! I think, both ways you are offering will break backwards compatibility. Besides that, I do think that people does not really change poll_interval often because it has effect on internals of the gem only. I think, we could set it to something like 5-10 seconds and remove this config option. How do you think?

**Comment by twonegatives** [comment]
> we could set it to something like 5-10 seconds and remove this config option

Sure, it could be a nice start to remove `poll_interval` from Readme, but I guess we can't remove it from `Sidekiq::Grouping::Config` completely due to backwards compatibility again...

> I think, both ways you are offering will break backwards compatibility

Moving `Sidekiq::Grouping.start!` would definetely do that and force us to release a new major version... But as of yml configuration file, there can be a workaround. I recall the way [limit_fetch](https://github.com/brainopia/sidekiq-limit_fetch) gets its configuration options: they have **both** yml and pure-ruby options setting:

    :limits:
      queue_name1: 5
      queue_name2: 10

```ruby
# And at the same time in ruby...
Sidekiq::Queue['queue_name1'].limit = 5
Sidekiq::Queue['queue_name2'].limit = 10
```

So, we could refactor `Sidekiq::Grouping::Config` not to set bare values like now:
```ruby
config.poll_interval = 3
```

but to take yml config in count. Something like:
```ruby
def poll_interval
  return @poll_interval if @poll_interval
  @poll_interval = value_from_yml || 3
end
```

and leave ruby-way param setting too.

Looking forward to see your thoughts on this.

**Comment by gzigzigzeo** [comment]
Yes, but why to remove ::Config completely? We can remove poll_interval from config, and that's it. It's easy and breaks nothing. Besides that, adding ability to read options from sidekiq.yml would be good addition.

**Comment by twonegatives** [comment]
> adding ability to read options from sidekiq.yml would be good addition.
Agreed. I'll make sidekiq-grouping to take options from sidekiq.yml then.

**Comment by twonegatives** [comment]
hey @gzigzigzeo sorry to ping, any update on this?

**Comment by gzigzigzeo** [comment]
@twonegatives hey, will try to check and merge in following days, really sorry for the delay, hot times with current project

**Comment by RKushnir** [comment]
Readme is misleading about being able to set `poll_interval` in the `sidekiq.yml`.

**Comment by gzigzigzeo** [comment]
@RKushnir No, it's there. https://github.com/gzigzigzeo/sidekiq-grouping#configuration

**Comment by RKushnir** [comment]
I mean, readme says I can(and should) set the option inside of sidekiq.yml, but the option is simply ignored.

**Comment by gzigzigzeo** [comment]
@RKushnir Ah, ok, will fix.

**Comment by twonegatives** [comment]
@RKushnir could you provide more info on how `poll_interval` is ignored please?
I've just tried to set a logger inside `FlusherObserver` for a successfull update and got the following output in console:
```ruby
2017-06-08T07:41:30.369Z 28497 TID-owcvm2ynk INFO: [Sidekiq::Grouping] update successfull
2017-06-08T07:41:33.372Z 28497 TID-owcvjnv1w INFO: [Sidekiq::Grouping] update successfull
2017-06-08T07:41:36.374Z 28497 TID-owcvjnv1w INFO: [Sidekiq::Grouping] update successfull
```
As you see, it logs each 3 seconds, which is default according to `Sidekiq::Grouping::Config`.
Now I set another value in `sidekiq.yml`:
```yml
grouping:
  :poll_interval: 10
```
And here is how console output changes:
```ruby
2017-06-08T07:42:55.117Z 28556 TID-ow8ty3dmk INFO: [Sidekiq::Grouping] update successfull
2017-06-08T07:43:05.119Z 28556 TID-ow8tfi43w INFO: [Sidekiq::Grouping] update successfull
2017-06-08T07:43:15.125Z 28556 TID-ow8tfi43w INFO: [Sidekiq::Grouping] update successfull
```
As you see, not it performs update each 10 seconds, just as we forced it to do in configuration file.

**Comment by RKushnir** [comment]
@twonegatives Looks like you're right. My mistake.

**Comment by nneufeld** [comment]
I was also seeing the option in `sidekiq.yml` ignored, then realized it's because the latest version published to RubyGems doesn't have the change in https://github.com/gzigzigzeo/sidekiq-grouping/pull/25

@gzigzigzeo Could you publish a new version of the gem?
