### ISSUE TITLE
Rename to sidekiq-grouping

### ISSUE THREAD

**Issue by ghempton** [gzigzigzeo/sidekiq-grouping#3]
I think grouping is very useful but is a totally different concept from sidekiq pro's [batches](https://github.com/mperham/sidekiq/wiki/Batches). This would help with confusion.

**Comment by gzigzigzeo** [comment]
Yes, I agree. How do you think what is the way do it genly? I mean, without unpromted breaking dependencies on a projects using my gem?

**Comment by gzigzigzeo** [comment]
Did it.
