### ISSUE TITLE
Consistent args for sidekiq inline tests

### ISSUE THREAD

**Issue by rahuljayaraman** [gzigzigzeo/sidekiq-grouping#36]
When sidekiq runs in [inline testing](https://github.com/mperham/sidekiq/wiki/Testing) mode, workers receive a single argument instead of a chunk/collection.

Would be nice if the behaviour is consistent in all environments viz. workers always receive a chunk.

Looks like the middleware simply yields as of now
https://github.com/gzigzigzeo/sidekiq-grouping/blob/a17d0809076d049571990130310c40993fb2d850/lib/sidekiq/grouping/middleware.rb#L5

Perhaps args could be changed in such cases?

**Comment by yrashk** [comment]
I also ran into this issue, thinking of fixing it (or come up with a new solution to this problem altogether). I suspect this project might have been gone stale / abandoned.
