### ISSUE TITLE
Jobs scheduled for the future are flushed instantly

### ISSUE THREAD

**Issue by pokonski** [gzigzigzeo/sidekiq-grouping#37]
### Steps to reproduce

```ruby
class SomeJob
  include Sidekiq::Worker
  sidekiq_options queue:   batch_flush_size: 2,      
                  batch_flush_interval: 5,
  def perform
  end
end
```

1. Schedule 2 jobs

```ruby
SomeJob.perform_at(1.day.from_now)
SomeJob.perform_at(2.days.from_now)
```

2. Start sidekiq process
3. Observe that jobs are flushed and performed

**Comment by dmitry** [comment]
There are no handler that checks `at` value:
https://github.com/gzigzigzeo/sidekiq-grouping/blob/master/lib/sidekiq/grouping/redis.rb#L14
