### ISSUE TITLE
interaction with sidekiq pro / reliable queueing

### ISSUE THREAD

**Issue by skyshard** [gzigzigzeo/sidekiq-grouping#6]
How does this interact with Sidekiq Pro and the reliable fetch / push mechanisms? 

It seems okay from my first read through the code, but I just wanted to confirm that I'm interpreting things properly:

First, jobs get `RPUSH`ed into a list and periodically plucked with the lua `PLUCK_SCRIPT` for queuing as regular Sidekiq jobs (at which point the reliable push code would take over). On the fetching end, `sidekiq-grouping` doesn't seem to modify logic there, so the `BRPOPLPUSH` stuff should still work as intended. 

There are probably two places where jobs could be lost- with redis connectivity issues at the initial `RPUSH`, and if there happened to be a crash after the `PLUCK_SCRIPT` ran but before the actual Sidekiq job push was called. Does that sound right to you?

Thanks!

**Comment by gzigzigzeo** [comment]
@skyshard Yes, everything sounds right for free Sidekiq version. But I did not ever use Sidekiq Pro, so I can not be sure that it will work without troubles. It should be tested.
